import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/ui/toaster";
import Provider from "../components/Provider"
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
            <main>
              {children}
              <Toaster />
            </main>
      </body>
      </html>
    </Provider >
  );
};
